
# ========= Secrets =========
secrets:
  tls_key:
    file: ${HOME}/data/certs/${DOMAIN}.key
  tls_cert:
    file: ${HOME}/data/certs/${DOMAIN}.crt

services:

  # ========= Maria DB =========
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 3s
      timeout: 2s
      retries: 20
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks: [web]

  # ========= WordPress =========
  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    entrypoint: ["/usr/local/bin/wp.sh"]
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    networks: [web]

  # ========= Nginx =========
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    secrets:
      - tls_key
      - tls_cert
    environment:
      - DOMAIN=qbeukelm.42.fr
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - wp_data:/var/www/html:ro
      - /home/qbeukelm/certs:/etc/nginx/certs
    networks: [web]

# ========= Volumes =========
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/certs

# ========= Networks =========
networks:
  web:
    driver: bridge
    name: web
