services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:custom
    container_name: srcs-mariadb-1
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      srcs_web:
        aliases: [mariadb]

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:custom
    container_name: srcs-wordpress-1
    restart: always
    entrypoint: ["/usr/local/bin/wp.sh"]
    depends_on:
      - mariadb
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: qbeukelm
      WORDPRESS_DB_PASSWORD: "1234"
    volumes:
      - wp_data:/var/www/html
    expose:
      - "9000"
    networks:
      srcs_web:
        aliases: [wordpress]

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:custom
    container_name: srcs-nginx-1
    restart: always
    depends_on:
      - wordpress
    env_file: .env
    environment:
      DOMAIN: ${DOMAIN}
      APP_HOST: wordpress
      APP_PORT: "9000"
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - wp_data:/var/www/html:ro
      - certs:/etc/nginx/certs
    networks:
      srcs_web:
        aliases: [nginx]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  certs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/certs

networks:
  srcs_web:
    name: srcs_web
    driver: bridge
