
version: '3'

services:
  mariadb:
    hostname: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD -h 127.0.0.1 --silent"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - db_data:/var/lib/mysql
    networks: [web]

  wordpress:
    hostname: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: unless_stopped
    depends_on:
      mariadb:
        condition: service_healthy
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    networks: [web]

  nginx:
    hostname: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    networks: [web]

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/qbeukelm/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/qbeukelm/data/wordpress

networks:
  web:
    driver: bridge

